common/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, re_path

from django.contrib import admin

from inventory import views
from imports.views import CheckFBaseView, ImportView, ImportedListView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('select2/', include('django_select2.urls')),
    path('dbdocs/', include('dbdocs.urls')),

    path('', views.HomeView.as_view(), name='home'),
    path('entity/<int:pk>/data/', views.HomeEntityData.as_view(), name='entity-data'),
    re_path(r'^entity/(?P<name>(owner|municipality))/(?P<pk>\d+)/$',
        views.EntityView.as_view(), name='entity'),
    re_path(r'^plotobs/(?P<name>(owner|municipality))/(?P<pk>\d+)/$',
        views.PlotObsDataView.as_view(), name='plotobs'),
    path('plotobs/<int:pk>/json/', views.PlotObsDetailJSONView.as_view(), name='plotobs-detail-json'),
    re_path(r'^entity/(?P<name>(owner|municipality))/(?P<pk>\d+)/(?P<year>\d+)/fbase/$',
        views.EntityFbaseExport.as_view(), name='entity-fbase'),
    path('owner/analysis/<int:pk>/<int:year>/', views.OwnerAnalysisView.as_view(), name='owner_analysis'),
    path('plotobs/<int:pk>/', views.PlotObsDetailView.as_view(output='html'), name='plotobs_detail'),
    path('plotobs/planned/<int:pk>/', views.PlotObsPlannedDetailView.as_view(),
        name='plotobs_planned_detail'),
    path('plotobs/planned/<int:pk>/edit/', views.PlotObsPlannedEditView.as_view(),
        name='plotobs_planned_edit'),
    path('plotobs/planned/<int:prot_pk>/multiedit/', views.PlotObsPlannedMultiEditView.as_view(),
        name='plotobs_planned_edit_multi'),
    path('plotobs/planned/<int:prot_pk>/multidelete/', views.PlotObsPlannedMultiDeleteView.as_view(),
        name='plotobs_planned_delete_multi'),
    path('plotobs/planned/new/<int:prot_pk>/', views.PlotObsPlannedNewView.as_view(),
        name='plotobs_planned_new'),
    path('plotobs/planned/<int:pk>/delete/', views.PlotObsPlannedDeleteView.as_view(),
        name='plotobs_planned_delete'),

    path('data/', views.DataPageView.as_view(), name='data_page'),
    path('data/grid/', views.DataGridView.as_view(), name='data_grid'),
    path('docs/', views.DocumentationView.as_view(), name='docs'),
    path('essences/', views.EssencesView.as_view(), name='essences'),
    path('essences/export/', views.EssencesExportView.as_view(), name='essences-export'),
    path('comp-fbase/', views.FBaseComparisonView.as_view(), name='fbase-comp'),
    path('protocoles/', views.ProtocolesView.as_view(), name='protocoles'),
    path('protocoles/<int:pk>/', views.ProtocoleDetailView.as_view(), name='protocole'),
    path('protocoles/<int:pk>/plots/', views.ProtocolePlotsView.as_view(), name='protocole_plots'),
    path('protocoles/<int:pk>/plots-conflicts/', views.ProtocoleConflictPlotsView.as_view(), name='protocole_plots_conflicts'),
    path('protocoles/<int:pk>/edition/', views.ProtocoleUpdateView.as_view(), name='protocole_edit'),
    path('protocoles/<int:pk>/import-plots/', views.ProtocoleImportPlotsView.as_view(), name='protocole_import'),
    path('protocoles/<int:pk>/topapp/', views.TopapGeoJSONView.as_view(), name='topapp-layer'),
    path('protocoles/nouveau/futur/', views.ProtocoleCreateView.as_view(typ='future'), name='protocole_addfuture'),
    path('protocoles/nouveau/passe/', views.ProtocoleCreateView.as_view(typ='passed'), name='protocole_addpassed'),
    path('protocoles/par_prop/', views.ProtocolesByOwnerView.as_view(), name='protocoles_by_owner'),
    path('rfinfo/', views.RFInfoView.as_view(), name='rfinfo'),

    path('import/topap/', views.TopApImportView.as_view(), name='import_topap'),
    path('import/all/', ImportedListView.as_view(), name='import_list'),
    path('import/form/<int:pk>/', ImportView.as_view(), name='import'),
    path('import/<int:pk>/checkfbase/', CheckFBaseView.as_view(), name='checkfbase'),
    path('vocabulary/<int:pk>/', views.VocabView.as_view(), name='vocabulary'),
]

if settings.DEBUG:
    from pathlib import Path
    from posixpath import normpath
    from django.utils._os import safe_join
    from django.views.static import serve

    def serve_index(request, path, document_root=None, **kwargs):
        ''' Simulate auto-loading of index.html '''
        norm_path = normpath(path).lstrip('/')
        fullpath = Path(safe_join(document_root, norm_path))
        if fullpath.is_dir():
            path = path + 'index.html'
        return serve(request, path, document_root=document_root, **kwargs)

    # Should be an Apache alias in production
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        '/manuel/', view=serve_index, document_root=settings.BASE_DIR / 'manuel' / 'site'
    )

inventory/models/models.py
import json
import math
import re
from decimal import Decimal, ROUND_HALF_UP

from django.contrib.auth.models import AbstractUser
from django.contrib.gis.db import models as gis_models
from django.contrib.gis.db.models.functions import Centroid, Envelope
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import OuterRef, Subquery
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.text import Truncator

from municipality.models import Municipality
from inventory.utils import diff_lines

TARIF_VOLUME_VD = {
    10: 7, 11: 8, 12: 9, 13: 10, 14: 11, 15: 13,
    16: 15, 17: 17, 18: 19, 19: 21, 20: 24, 21: 27,
    22: 31, 23: 35, 24: 39, 25: 43, 26: 48, 27: 53,
    28: 58, 29: 64, 30: 70, 31: 76, 32: 82, 33: 88,
    34: 95, 35: 102, 36: 109, 37: 117, 38: 125, 39: 133,
    40: 142, 41: 151, 42: 160, 43: 169, 44: 178, 45: 188,
    46: 198, 47: 208, 48: 218, 49: 229, 50: 240, 51: 251,
    52: 262, 53: 273, 54: 284, 55: 296, 56: 308, 57: 320,
    58: 333, 59: 346, 60: 359, 61: 373, 62: 387, 63: 401,
    64: 415, 65: 429, 66: 444, 67: 459, 68: 475, 69: 491,
    70: 507, 71: 523, 72: 540, 73: 557, 74: 574, 75: 591,
    76: 608, 77: 625, 78: 643, 79: 661, 80: 679, 81: 697,
    82: 715, 83: 733, 84: 752, 85: 771, 86: 790, 87: 809,
    88: 828, 89: 848, 90: 868, 91: 888, 92: 908, 93: 928,
    94: 949, 95: 970, 96: 991, 97: 1012, 98: 1033, 99: 1055,
    100: 1077, 101: 1099, 102: 1121, 103: 1143, 104: 1166, 105: 1189,
    106: 1212, 107: 1236, 108: 1260, 109: 1284, 110: 1310, 111: 1337,
}


class User(AbstractUser):
    phone = models.CharField("Téléphone", max_length=40, blank=True)

    class Meta:
        db_table = 'auth_user'

    def __str__(self):
        return self.get_full_name() or self.username


class Vocabulary(models.Model):
    name = models.CharField(max_length=250)
    comment = models.TextField(blank=True)

    class Meta:
        db_table = 'vocabulary'
        verbose_name = 'vocabulaire'
        ordering = ('name',)

    def __str__(self):
        return self.name


class VocabValue(models.Model):
    vocab = models.ForeignKey(Vocabulary, on_delete=models.CASCADE)
    code = models.CharField(max_length=1)
    label = models.CharField(max_length=100)
    class Meta:
        db_table = 'vocabvalue'
        verbose_name = 'valeur de vocabulaire'

    def __str__(self):
        return "%s (%s)" % (self.label, self.code)


class OwnerType(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    num_code = models.SmallIntegerField()
    alpha_code = models.CharField(max_length=2)

    class Meta:
        db_table = 'owner_type'
        verbose_name = 'type de propriétaire'
        indexes = [models.Index(name='alpha_code', fields=['alpha_code'])]

    def __str__(self):
        return self.name


class Owner(models.Model):
    name = models.CharField(max_length=120, blank=True)
    typ = models.ForeignKey(OwnerType, db_column='type_id', on_delete=models.PROTECT)
    num = models.CharField(max_length=3, help_text="Position Ipasmofix")

    class Meta:
        db_table = 'owner'
        verbose_name = "propriétaire"
        indexes = [models.Index(name='num_index', fields=['num'])]
        unique_together = ('typ', 'num')

    def __str__(self):
        return self.title

    @property
    def code(self):
        return "%s%s" % (self.typ.alpha_code, self.num)

    @classmethod
    def get_by_code(cls, code):
        try:
            return Owner.objects.get(typ__alpha_code=code[0], num=code[1:4])
        except (Owner.DoesNotExist, IndexError):
            return None

    @property
    def title(self):
        num = self.code
        if self.name:
            num += " - %s" % self.name
        return num


class PlotQuerySet(models.QuerySet):
    def as_geojson(self):
        geojson = {"type": "FeatureCollection", "features": []}
        for obj in self:
            obj.center.transform(4326)
            geojson['features'].append({
                "type": "Feature",
                "id": obj.pk,
                "geometry": json.loads(obj.center.json),
                "properties": {"sealevel": obj.sealevel},
            })
        return geojson


class Plot(gis_models.Model):
    center = gis_models.PointField(srid=2056, verbose_name="Coordonnées")
    sealevel = models.SmallIntegerField("Altitude", blank=True, null=True)
    # Should probably not be optional finally
    municipality = models.ForeignKey(Municipality, null=True, blank=True, on_delete=models.PROTECT)

    objects = PlotQuerySet.as_manager()

    class Meta:
        db_table = 'plot'
        verbose_name = 'placette'

    def __str__(self):
        return "Placette x=%d y=%d" % (self.center.x, self.center.y)

    def as_geojson(self, srid=None, geom_field='center', obs_urls=True):
        geom = getattr(self, geom_field)
        if (srid is not None and srid != geom.srid):
            geom = geom.transform(srid, clone=True)
        geojson = {
            "type": "Feature",
            "id": self.pk,
            "properties": {
                "id": self.pk,
                "sealevel": self.sealevel,
            },
            "geometry": json.loads(geom.json),
        }
        if obs_urls:
            geojson["properties"]["obsURLs"] = {
                str(obs.year): reverse('plotobs-detail-json', args=[obs.pk])
                for obs in self.plotobs_set.all()
            }
        return geojson


class Density(models.Model):
    name = models.CharField(max_length=50)
    code = models.SmallIntegerField()
    surface = models.IntegerField("Surface représentée en m2")

    class Meta:
        db_table = 'density'
        verbose_name = 'densité'

    def __str__(self):
        return self.name


class Intervention(models.Model):
    name = models.CharField(max_length=50)
    code = models.CharField("Code fbase", max_length=1, blank=True)
    default_pos = models.SmallIntegerField(null=True, blank=True, unique=True,
        help_text="Position par défaut (0-9) de cette intervention sur la fiche Ipasmofix")
    active = models.BooleanField(default=False)

    class Meta:
        db_table = 'intervention'
        ordering = ('name',)

    def __str__(self):
        return self.name


class Nature(models.Model):
    code = models.SmallIntegerField()
    description = models.CharField(max_length=255)
    woods = models.BooleanField("Boisé", default=True)

    class Meta:
        db_table = 'nature'
        ordering = ('code',)

    def __str__(self):
        return Truncator(self.description).chars(45)


class Protocol(models.Model):
    name = models.CharField("Nom", max_length=200, blank=True)
    pfile = models.FileField(upload_to='protocols', blank=True, verbose_name="Fichier de protocole")
    year = models.SmallIntegerField("Année d'inventaire")
    passed = models.BooleanField(default=True, help_text="L’inventaire est terminé.")
    default_density = models.ForeignKey(
        Density, on_delete=models.PROTECT, verbose_name="Densité par défaut", null=True, blank=True
    )
    geom = gis_models.MultiPolygonField(srid=2056, verbose_name="Surface d’inventaire", null=True, blank=True)
    inv_date = models.CharField("Période d’inventaire", max_length=200)
    draft = models.BooleanField(default=False)
    # Vocabularies for reserved fields
    vocab_posp8 = models.ForeignKey(Vocabulary, verbose_name="Champ libre 1",
        help_text="Vocabulaire du champ libre 1 (PARC, position 8)",
        null=True, blank=True, on_delete=models.PROTECT, related_name='+')
    vocab_posp9 = models.ForeignKey(Vocabulary, verbose_name="Champ libre 2",
        help_text="Vocabulaire du champ libre 2 (PARC, position 9)",
        null=True, blank=True, on_delete=models.PROTECT, related_name='+')
    vocab_posd6 = models.ForeignKey(Vocabulary, verbose_name="Champ libre 3",
        help_text="Vocabulaire du champ libre 3 (DESP, position 6)",
        null=True, blank=True, on_delete=models.PROTECT, related_name='+')
    vocab_posd7 = models.ForeignKey(Vocabulary, verbose_name="Champ libre 4",
        help_text="Vocabulaire du champ libre 4 (DESP, position 7)",
        null=True, blank=True, on_delete=models.PROTECT, related_name='+')
    interv_0 = models.ForeignKey(Intervention, related_name='+', null=True, blank=True, on_delete=models.PROTECT)
    interv_1 = models.ForeignKey(Intervention, related_name='+', null=True, blank=True, on_delete=models.PROTECT)
    interv_2 = models.ForeignKey(Intervention, related_name='+', null=True, blank=True, on_delete=models.PROTECT)
    interv_3 = models.ForeignKey(Intervention, related_name='+', null=True, blank=True, on_delete=models.PROTECT)
    interv_4 = models.ForeignKey(Intervention, related_name='+', null=True, blank=True, on_delete=models.PROTECT)
    interv_5 = models.ForeignKey(Intervention, related_name='+', null=True, blank=True, on_delete=models.PROTECT)
    interv_6 = models.ForeignKey(Intervention, related_name='+', null=True, blank=True, on_delete=models.PROTECT)
    interv_7 = models.ForeignKey(Intervention, related_name='+', null=True, blank=True, on_delete=models.PROTECT)
    interv_8 = models.ForeignKey(Intervention, related_name='+', null=True, blank=True, on_delete=models.PROTECT)
    interv_9 = models.ForeignKey(Intervention, related_name='+', null=True, blank=True, on_delete=models.PROTECT)
    spec_pos1 = models.ForeignKey('TreeSpecies', verbose_name="Essence en position 1",
        null=True, blank=True, related_name='+', on_delete=models.PROTECT)
    spec_pos2 = models.ForeignKey('TreeSpecies', verbose_name="Essence en position 2",
        null=True, blank=True, related_name='+', on_delete=models.PROTECT)
    spec_pos3 = models.ForeignKey('TreeSpecies', verbose_name="Essence en position 3",
        null=True, blank=True, related_name='+', on_delete=models.PROTECT)

inventory/templates/docs.html
{% extends "base.html" %}

{% block content %}
<ul>
  <li><a href="/manuel/">Guide d'utilisation des inventaires forestiers</a></li>
  <li><a href="{% url 'protocoles' %}">Protocoles d'inventaires</a></li>
  <li><a href="{% url 'fbase-comp' %}">Outil de comparaison de fichiers texte</a></li>
  <li>
      Instances de test: <a href="https://testwww.inv-vd.ch">testwww.inv-vd.ch</a> et
      <a href="https://testmobile.inv-vd.ch">testmobile.inv-vd.ch</a>
  </li>
</ul>

<h2>Introspection de la base de données</h2>
<ul>
    <li><a href="{% url 'table-list' %}">Tables de la base de données</a></li>
    <li><a href="{% url 'view-list' %}">Vues de la base de données</a></li>
</ul>
<ul>
    <li><a href="{% url 'import_topap' %}">Importer le fichier Shape Topap</a></li>
</ul>

<h2>Documents</h2>
<ul>
{% for doc in docs %}
    <li><a href="{{ MEDIA_URL }}{{ doc.doc }}">{{ doc.title }}</a> <small>({{ doc.fformat }}, {{ doc.date }})</small></li>
{% endfor %}
</ul>

<h2>Définitions</h2>
<p><a href="{% url 'essences' %}">Liste des essences</a></p>
<p><i>Voir aussi: <a href="https://www.lfi.ch/glossar/glossar-fr.php">Glossaire de l'IFN</a></i></p>
<!--dl>
    <dt>...</dt>
    <dd>...</dd>
</dl-->
{% endblock %}

inventory/templates/essences.html
{% extends "base.html" %}

{% block content %}

<h1>Essences</h1>

<form action="{% url 'essences-export' %}">
    <button type="submit">Exporter le fichier pour la pince</button>
</form>

<h2>Essences «actives»</h2>
<p>Ces essences peuvent être saisies lors de nouveaux inventaires. Ce sont ces essences qui sont exportées en cliquant sur le bouton ci-dessus.</p>
<table>
    {% for essence in actives %}
    <tr><td>{{ essence.order|default_if_none:'-' }}.</td>
        <td>{{ essence.species }}</td>
        <td>{{ essence.abbrev }}</td>
    </tr>
    {% endfor %}
</table>

<h2>Essences «historiques»</h2>
<p>Ces essences ont été utilisées par le passé, mais ne sont plus disponibles lors de nouveaux inventaires.</p>

<ul>
    {% for essence in inactives %}
    <li>{{ essence }}{% if essence.abbrev %} ({{ essence.abbrev }}){% endif %}</li>
    {% endfor %}
</ul>

{% endblock %}

inventory/templates/index.html
{% extends "base.html" %}

{% block extra_head %}
<style>
span.expander { cursor: pointer; font-weight: bold; }
tbody:not(.expanded) > tr:not(.title) { display: none; }
tbody:not(.expanded) span.expander::before { content: '+'; }
tbody.expanded span.expander::before { content: '—'; }
tr.wait td { text-align: center; }
.lastli { list-style: none; margin-top: 0.4em; }
</style>
<script>
function toggleBody(span) {
    const tbody = span.closest('tbody');
    tbody.classList.toggle('expanded');
    if (tbody.classList.contains('unloaded')) {
        // Load dynamically
        fetch(tbody.dataset.url).then(response => {
            return response.text().then(text => {
                tbody.querySelector('tr.wait').remove();
                tbody.insertAdjacentHTML('beforeend', text);
            });
        });
        tbody.classList.remove('unloaded');
    }
}

document.addEventListener("DOMContentLoaded", function(){
    const expanders = document.querySelectorAll("span.expander");
    Array.from(expanders).forEach(span => {
        span.addEventListener('click', function (ev) { toggleBody(span); });
    });
});
</script>
{% endblock %}

{% block content %}

<div>
    <h2>Inventaires {{ cur_year }}</h2>
    <ul>
    {% for inv in inventaires %}
        <li><a href="{% url 'protocole' inv.pk %}">{{ inv }}</a></li>
    {% endfor %}
    {% if perms.inventory.add_protocol %}
        <li class="lastli"><a class="btn" href="{% url 'protocole_addfuture' %}">Nouvel inventaire…</a></li>
    {% endif %}
    </ul>
</div>

<div class="tabs">
    <ul class="tabs">
      <li {% if col1_name == "Commune" %}class="active"{% endif %}>
          <a href="{% url 'home'  %}?by=municipality">Par commune</a></li>
      <li {% if col1_name == "Propriétaire" %}class="active"{% endif %}>
          <a href="{% url 'home'  %}?by=owner">Par propriétaire</a></li>
    </ul>
</div>

<table class="numbers">
    <thead><tr>
        <th>{{ col1_name }}
            <div class="icons"><img class="info" src="{% static 'img/info.png' %}" title="{{ col1_descr }}"></div>
        </th>
        <th>Année</th>
        <th>Nombre de placettes
            <div class="icons"><img class="info" src="{% static 'img/info.png' %}" title="Nombre de placettes par propriétaire ou commune politique"></div>
        </th>
        <th>Nombre de tiges (≥16cm)/hectare
            <div class="icons">
                <img class="info" src="{% static 'img/info.png' %}" title="Nombre d'arbres d'un peuplement, au total ou par unité de surface, en général nombre de tiges par hectare.">
                <img class="info" src="{% static 'img/methode.png' %}" title="Somme des arbres (tiges) par hectare ayant un diamètre plus grand que 16 cm.">
            </div>
        </th>
        <th>Volume (m<sup>3</sup>) tarif vaudois/hectare
            <div class="icons">
                <img class="info" src="{% static 'img/info.png' %}" title="Volume de bois sur pied d'une surface donnée (matériel sur pied), basé sur le tarif vaudois.">
                <img class="info" src="{% static 'img/methode.png' %}" title="Fonction: ksp_vd_tarif_vaudois_fonction (-0.033804 - (0.010468*diamètre) + (0.001184*diamètre*diamètre)">
            </div>
        </th>
        <th>Surface terrière (m<sup>2</sup>)/hectare
            <div class="icons">
                <img class="info" src="{% static 'img/info.png' %}" title="Surface de la section transversale d'un arbre à 1.3 m de hauteur (emplacement de la mesure du DHP), resp. total des sections transversales de tous les arbres d'un peuplement.">
                <img class="info" src="{% static 'img/methode.png' %}" title="Fonction: ksp_vd_surface_terriere (pi() * (diamètre*diamètre) / 4)">
            </div>
        </th>
        <th>Diamètre moyen (cm)
            <div class="icons">
                <img class="info" src="{% static 'img/info.png' %}" title="Moyenne des diamètres à hauteur de poitrine de tous les arbres mesurés d'un échantillon.">
                <img class="info" src="{% static 'img/methode.png' %}" title="Fonction: moyenne(tree.diameter)">
            </div>
        </th>
        <th>Volume de l'arbre moyen (m<sup>3</sup>)
            <div class="icons">
                <img class="info" src="{% static 'img/info.png' %}" title="Volume de la moyenne des diamètres à hauteur de poitrine de tous les arbres mesurés d'un échantillon.">
                <img class="info" src="{% static 'img/methode.png' %}" title="Idem Volume">
            </div>
        </th>
        <th>Surface terrière de l'arbre moyen (cm<sup>2</sup>)
            <div class="icons">
                <img class="info" src="{% static 'img/info.png' %}" title="Surface terrière de la moyenne des diamètres à hauteur de poitrine de tous les arbres mesurés d'un échantillon.">
                <img class="info" src="{% static 'img/methode.png' %}" title="Idem Surface terrière">
            </div>
        </th>
        <th>Surface forestière théorique
            <div class="icons">
                <img class="info" src="{% static 'img/info.png' %}" title="Ensemble de toutes les surfaces qui sont désignées comme forêt selon la définition de la DGNP.">
            </div>
        </th>
    </tr></thead>
{% if view_by == 'owner' %}
    {% for entity in entities %}
        <tbody class="dynamic unloaded" data-url="{% url 'entity-data' entity.pk %}">
            <tr class="title"><td colspan="10"><span class="expander"> {{ entity }}</span></td></tr>
            <tr class="wait"><td colspan="10"><img src="{% static 'img/indicator.gif' %}"></td></tr>
        </tbody>
    {% endfor %}
{% else %}
    <tbody class="expanded">
    {% for line in data %}
    <tr><td class="{% ifchanged line.entity %}normal{% else %}duplicate{% endifchanged %}">
        <a href="{{ line.entity_url }}">{{ line.entity }}</a></td>
        <td>{{ line.protocol.year }}</td>
        <td class="right">{{ line.plot_numb }}</td>
        <td class="right">{{ line.tree_numb_ha|floatformat:2 }}</td>
        <td class="right">{{ line.vol_vd_ha|floatformat:2 }}</td>
        <td class="right">{{ line.surf_terr_ha|floatformat:2 }}</td>
        <td class="right">{{ line.diam_mean|floatformat:2 }}</td>
        <td class="right">{{ line.vol_mean|floatformat:2 }}</td>
        <td class="right">{{ line.surf_terr_tree_mean|floatformat:2 }}</td>
        <td class="right">{{ line.surf_forest|floatformat:2 }}</td>
    </tr>
    {% endfor %}
    </tbody>
{% endif %}
</table>
<div class="dbview">[data based on {{ metadata.db_table }}]</div>

{% endblock %}

inventory/templates/protocole_new.html
{% extends "base.html" %}

{% block extra_head %}
<style>
  label { font-size: small; color: #333; }
  #id_name { width: 100%; }
  #id_comments { height: 5em; width: 100%; }
  .row { margin-top: 0.4em; } 
</style>
{% endblock %}

{% block content %}
<h2>Nouvel inventaire</h2>

<div id="mainwrapper">
    <form method="post">{% csrf_token %}
        <div class="row">{{ form.non_field_errors }}</div>
        <div class="row">{{ form.name.label_tag }} {{ form.name.errors }}<br>{{ form.name }}</div>

        <div class="container row">
            <div>{{ form.year.label_tag }} {{ form.year.errors }}<br>{{ form.year }}</div>
            <div>{{ form.inv_date.label_tag }} {{ form.inv_date.errors }}<br>{{ form.inv_date }}</div>
            {% if form.default_density %}
            <div>{{ form.default_density.label_tag }} {{ form.default_density.errors }}<br>{{ form.default_density }}</div>
            {% endif %}
        </div>
        <div class="row">
            {{ form.comments.label_tag }} {{ form.comments.errors }}<br>{{ form.comments }}
        </div>
        <div class="row"><button type="submit">Créer</button></div>
    </form>
</div>
{% endblock %}

inventory/templates/protocoles_by_owner.html
{% extends "base.html" %}
{% load display %}

{% block extra_head %}
<style>
table.list { width: 100%; }
tr.new-owner td { border-top: 2px solid black; }
</style>
{% endblock %}

{% block content %}
<h2>Liste des protocoles d'inventaire</h2>
<p>Dans cet affichage, les protocoles apparaissent autant de fois qu'ils ont de propriétaire.</p>

<p style="text-align: right;"><a href="{% url 'admin:inventory_protocol_add' %}">Ajouter un protocole</a></p>

<div class="tabs">
    {% url 'protocoles' as prot %}
    {% url 'protocoles_by_owner' as prot_by_owner %}
    <ul class="tabs">
      <li {% if request.path == prot %}class="active"{% endif %}>
          <a href="{{ prot }}">Par année</a></li>
      <li {% if request.path == prot_by_owner %}class="active"{% endif %}>
          <a href="{{ prot_by_owner }}">Par propriétaire</a></li>
    </ul>
</div>

<table class="list">
  <tr><th>Année</th><th>Fichier</th><th>Propriétaire</th><th>Points importés</th></tr>
{% for owner in object_list %}
  {% for protocol in owner.protocol_set.all %}
      <tr class="{% ifchanged owner %}new-owner{% endifchanged %}{{ protocol.draft|yesno:'draft,' }}">
          <td>{{ protocol.year }}</td>
          <td><a href="{{ MEDIA_URL }}{{ protocol.pfile }}">{{ protocol.pfile|basename }}</a></td>
          <td>{{ owner }}</td>
          <td>{{ protocol.plotobs__count }}</td>
          <td><a href="{% url 'admin:inventory_protocol_change' protocol.pk %}"><img src="{% static 'img/edit.png' %}" width="20"></a></td>
      </tr>
  {% endfor %}
{% endfor %}
</table>
{% endblock %}

inventory/templates/vocabulary_detail.html
<div class="vocabulary">
{% for value in object.vocabvalue_set.all %}
  <p><span class="value_code">{{ value.code }}</span> &mdash;
     <span class="value_label">{{ value.label }}</span></p>
{% endfor %}
</div>