common/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, re_path

from django.contrib import admin

from inventory import views
from imports.views import CheckFBaseView, ImportView, ImportedListView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('select2/', include('django_select2.urls')),
    path('dbdocs/', include('dbdocs.urls')),

    path('', views.HomeView.as_view(), name='home'),
    path('entity/<int:pk>/data/', views.HomeEntityData.as_view(), name='entity-data'),
    re_path(r'^entity/(?P<name>(owner|municipality))/(?P<pk>\d+)/$',
        views.EntityView.as_view(), name='entity'),
    re_path(r'^plotobs/(?P<name>(owner|municipality))/(?P<pk>\d+)/$',
        views.PlotObsDataView.as_view(), name='plotobs'),
    path('plotobs/<int:pk>/json/', views.PlotObsDetailJSONView.as_view(), name='plotobs-detail-json'),
    re_path(r'^entity/(?P<name>(owner|municipality))/(?P<pk>\d+)/(?P<year>\d+)/fbase/$',
        views.EntityFbaseExport.as_view(), name='entity-fbase'),
    path('owner/analysis/<int:pk>/<int:year>/', views.OwnerAnalysisView.as_view(), name='owner_analysis'),
    path('plotobs/<int:pk>/', views.PlotObsDetailView.as_view(output='html'), name='plotobs_detail'),
    path('plotobs/planned/<int:pk>/', views.PlotObsPlannedDetailView.as_view(),
        name='plotobs_planned_detail'),
    path('plotobs/planned/<int:pk>/edit/', views.PlotObsPlannedEditView.as_view(),
        name='plotobs_planned_edit'),
    path('plotobs/planned/<int:prot_pk>/multiedit/', views.PlotObsPlannedMultiEditView.as_view(),
        name='plotobs_planned_edit_multi'),
    path('plotobs/planned/<int:prot_pk>/multidelete/', views.PlotObsPlannedMultiDeleteView.as_view(),
        name='plotobs_planned_delete_multi'),
    path('plotobs/planned/new/<int:prot_pk>/', views.PlotObsPlannedNewView.as_view(),
        name='plotobs_planned_new'),
    path('plotobs/planned/<int:pk>/delete/', views.PlotObsPlannedDeleteView.as_view(),
        name='plotobs_planned_delete'),

    path('data/', views.DataPageView.as_view(), name='data_page'),
    path('data/grid/', views.DataGridView.as_view(), name='data_grid'),
    path('docs/', views.DocumentationView.as_view(), name='docs'),
    path('essences/', views.EssencesView.as_view(), name='essences'),
    path('essences/export/', views.EssencesExportView.as_view(), name='essences-export'),
    path('comp-fbase/', views.FBaseComparisonView.as_view(), name='fbase-comp'),
    path('protocoles/', views.ProtocolesView.as_view(), name='protocoles'),
    path('protocoles/<int:pk>/', views.ProtocoleDetailView.as_view(), name='protocole'),
    path('protocoles/<int:pk>/plots/', views.ProtocolePlotsView.as_view(), name='protocole_plots'),
    path('protocoles/<int:pk>/plots-conflicts/', views.ProtocoleConflictPlotsView.as_view(), name='protocole_plots_conflicts'),
    path('protocoles/<int:pk>/edition/', views.ProtocoleUpdateView.as_view(), name='protocole_edit'),
    path('protocoles/<int:pk>/import-plots/', views.ProtocoleImportPlotsView.as_view(), name='protocole_import'),
    path('protocoles/<int:pk>/topapp/', views.TopapGeoJSONView.as_view(), name='topapp-layer'),
    path('protocoles/nouveau/futur/', views.ProtocoleCreateView.as_view(typ='future'), name='protocole_addfuture'),
    path('protocoles/nouveau/passe/', views.ProtocoleCreateView.as_view(typ='passed'), name='protocole_addpassed'),
    path('protocoles/par_prop/', views.ProtocolesByOwnerView.as_view(), name='protocoles_by_owner'),
    path('rfinfo/', views.RFInfoView.as_view(), name='rfinfo'),

    path('import/topap/', views.TopApImportView.as_view(), name='import_topap'),
    path('import/all/', ImportedListView.as_view(), name='import_list'),
    path('import/form/<int:pk>/', ImportView.as_view(), name='import'),
    path('import/<int:pk>/checkfbase/', CheckFBaseView.as_view(), name='checkfbase'),
    path('vocabulary/<int:pk>/', views.VocabView.as_view(), name='vocabulary'),
]

if settings.DEBUG:
    from pathlib import Path
    from posixpath import normpath
    from django.utils._os import safe_join
    from django.views.static import serve

    def serve_index(request, path, document_root=None, **kwargs):
        ''' Simulate auto-loading of index.html '''
        norm_path = normpath(path).lstrip('/')
        fullpath = Path(safe_join(document_root, norm_path))
        if fullpath.is_dir():
            path = path + 'index.html'
        return serve(request, path, document_root=document_root, **kwargs)

    # Should be an Apache alias in production
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        '/manuel/', view=serve_index, document_root=settings.BASE_DIR / 'manuel' / 'site'
    )

inventory/models/models.py
import json
import math
import re
from decimal import Decimal, ROUND_HALF_UP

from django.contrib.auth.models import AbstractUser
from django.contrib.gis.db import models as gis_models
from django.contrib.gis.db.models.functions import Centroid, Envelope
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import OuterRef, Subquery
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.text import Truncator

from municipality.models import Municipality
from inventory.utils import diff_lines

TARIF_VOLUME_VD = {
    10: 7, 11: 8, 12: 9, 13: 10, 14: 11, 15: 13,
    16: 15, 17: 17, 18: 19, 19: 21, 20: 24, 21: 27,
    22: 31, 23: 35, 24: 39, 25: 43, 26: 48, 27: 53,
    28: 58, 29: 64, 30: 70, 31: 76, 32: 82, 33: 88,
    34: 95, 35: 102, 36: 109, 37: 117, 38: 125, 39: 133,
    40: 142, 41: 151, 42: 160, 43: 169, 44: 178, 45: 188,
    46: 198, 47: 208, 48: 218, 49: 229, 50: 240, 51: 251,
    52: 262, 53: 273, 54: 284, 55: 296, 56: 308, 57: 320,
    58: 333, 59: 346, 60: 359, 61: 373, 62: 387, 63: 401,
    64: 415, 65: 429, 66: 444, 67: 459, 68: 475, 69: 491,
    70: 507, 71: 523, 72: 540, 73: 557, 74: 574, 75: 591,
    76: 608, 77: 625, 78: 643, 79: 661, 80: 679, 81: 697,
    82: 715, 83: 733, 84: 752, 85: 771, 86: 790, 87: 809,
    88: 828, 89: 848, 90: 868, 91: 888, 92: 908, 93: 928,
    94: 949, 95: 970, 96: 991, 97: 1012, 98: 1033, 99: 1055,
    100: 1077, 101: 1099, 102: 1121, 103: 1143, 104: 1166, 105: 1189,
    106: 1212, 107: 1236, 108: 1260, 109: 1284, 110: 1310, 111: 1337,
}


class User(AbstractUser):
    phone = models.CharField("Téléphone", max_length=40, blank=True)

    class Meta:
        db_table = 'auth_user'

    def __str__(self):
        return self.get_full_name() or self.username


class Vocabulary(models.Model):
    name = models.CharField(max_length=250)
    comment = models.TextField(blank=True)

    class Meta:
        db_table = 'vocabulary'
        verbose_name = 'vocabulaire'
        ordering = ('name',)

    def __str__(self):
        return self.name


class VocabValue(models.Model):
    vocab = models.ForeignKey(Vocabulary, on_delete=models.CASCADE)
    code = models.CharField(max_length=1)
    label = models.CharField(max_length=100)
    class Meta:
        db_table = 'vocabvalue'
        verbose_name = 'valeur de vocabulaire'

    def __str__(self):
        return "%s (%s)" % (self.label, self.code)


class OwnerType(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    num_code = models.SmallIntegerField()
    alpha_code = models.CharField(max_length=2)

    class Meta:
        db_table = 'owner_type'
        verbose_name = 'type de propriétaire'
        indexes = [models.Index(name='alpha_code', fields=['alpha_code'])]

    def __str__(self):
        return self.name


class Owner(models.Model):
    name = models.CharField(max_length=120, blank=True)
    typ = models.ForeignKey(OwnerType, db_column='type_id', on_delete=models.PROTECT)
    num = models.CharField(max_length=3, help_text="Position Ipasmofix")

    class Meta:
        db_table = 'owner'
        verbose_name = "propriétaire"
        indexes = [models.Index(name='num_index', fields=['num'])]
        unique_together = ('typ', 'num')

    def __str__(self):
        return self.title

    @property
    def code(self):
        return "%s%s" % (self.typ.alpha_code, self.num)

    @classmethod
    def get_by_code(cls, code):
        try:
            return Owner.objects.get(typ__alpha_code=code[0], num=code[1:4])
        except (Owner.DoesNotExist, IndexError):
            return None

    @property
    def title(self):
        num = self.code
        if self.name:
            num += " - %s" % self.name
        return num


class PlotQuerySet(models.QuerySet):
    def as_geojson(self):
        geojson = {"type": "FeatureCollection", "features": []}
        for obj in self:
            obj.center.transform(4326)
            geojson['features'].append({
                "type": "Feature",
                "id": obj.pk,
                "geometry": json.loads(obj.center.json),
                "properties": {"sealevel": obj.sealevel},
            })
        return geojson


class Plot(gis_models.Model):
    center = gis_models.PointField(srid=2056, verbose_name="Coordonnées")
    sealevel = models.SmallIntegerField("Altitude", blank=True, null=True)
    # Should probably not be optional finally
    municipality = models.ForeignKey(Municipality, null=True, blank=True, on_delete=models.PROTECT)

    objects = PlotQuerySet.as_manager()

    class Meta:
        db_table = 'plot'
        verbose_name = 'placette'

    def __str__(self):
        return "Placette x=%d y=%d" % (self.center.x, self.center.y)

    def as_geojson(self, srid=None, geom_field='center', obs_urls=True):
        geom = getattr(self, geom_field)
        if (srid is not None and srid != geom.srid):
            geom = geom.transform(srid, clone=True)
        geojson = {
            "type": "Feature",
            "id": self.pk,
            "properties": {
                "id": self.pk,
                "sealevel": self.sealevel,
            },
            "geometry": json.loads(geom.json),
        }
        if obs_urls:
            geojson["properties"]["obsURLs"] = {
                str(obs.year): reverse('plotobs-detail-json', args=[obs.pk])
                for obs in self.plotobs_set.all()
            }
        return geojson


class Density(models.Model):
    name = models.CharField(max_length=50)
    code = models.SmallIntegerField()
    surface = models.IntegerField("Surface représentée en m2")

    class Meta:
        db_table = 'density'
        verbose_name = 'densité'

    def __str__(self):
        return self.name


class Intervention(models.Model):
    name = models.CharField(max_length=50)
    code = models.CharField("Code fbase", max_length=1, blank=True)
    default_pos = models.SmallIntegerField(null=True, blank=True, unique=True,
        help_text="Position par défaut (0-9) de cette intervention sur la fiche Ipasmofix")
    active = models.BooleanField(default=False)

    class Meta:
        db_table = 'intervention'
        ordering = ('name',)

    def __str__(self):
        return self.name


class Nature(models.Model):
    code = models.SmallIntegerField()
    description = models.CharField(max_length=255)
    woods = models.BooleanField("Boisé", default=True)

    class Meta:
        db_table = 'nature'
        ordering = ('code',)

    def __str__(self):
        return Truncator(self.description).chars(45)


class Protocol(models.Model):
    name = models.CharField("Nom", max_length=200, blank=True)
    pfile = models.FileField(upload_to='protocols', blank=True, verbose_name="Fichier de protocole")
    year = models.SmallIntegerField("Année d'inventaire")
    passed = models.BooleanField(default=True, help_text="L’inventaire est terminé.")
    default_density = models.ForeignKey(
        Density, on_delete=models.PROTECT, verbose_name="Densité par défaut", null=True, blank=True
    )
    geom = gis_models.MultiPolygonField(srid=2056, verbose_name="Surface d’inventaire", null=True, blank=True)
    inv_date = models.CharField("Période d’inventaire", max_length=200)
    draft = models.BooleanField(default=False)
    # Vocabularies for reserved fields
    vocab_posp8 = models.ForeignKey(Vocabulary, verbose_name="Champ libre 1",
        help_text="Vocabulaire du champ libre 1 (PARC, position 8)",
        null=True, blank=True, on_delete=models.PROTECT, related_name='+')
    vocab_posp9 = models.ForeignKey(Vocabulary, verbose_name="Champ libre 2",
        help_text="Vocabulaire du champ libre 2 (PARC, position 9)",
        null=True, blank=True, on_delete=models.PROTECT, related_name='+')
    vocab_posd6 = models.ForeignKey(Vocabulary, verbose_name="Champ libre 3",
        help_text="Vocabulaire du champ libre 3 (DESP, position 6)",
        null=True, blank=True, on_delete=models.PROTECT, related_name='+')
    vocab_posd7 = models.ForeignKey(Vocabulary, verbose_name="Champ libre 4",
        help_text="Vocabulaire du champ libre 4 (DESP, position 7)",
        null=True, blank=True, on_delete=models.PROTECT, related_name='+')
    interv_0 = models.ForeignKey(Intervention, related_name='+', null=True, blank=True, on_delete=models.PROTECT)
    interv_1 = models.ForeignKey(Intervention, related_name='+', null=True, blank=True, on_delete=models.PROTECT)
    interv_2 = models.ForeignKey(Intervention, related_name='+', null=True, blank=True, on_delete=models.PROTECT)
    interv_3 = models.ForeignKey(Intervention, related_name='+', null=True, blank=True, on_delete=models.PROTECT)
    interv_4 = models.ForeignKey(Intervention, related_name='+', null=True, blank=True, on_delete=models.PROTECT)
    interv_5 = models.ForeignKey(Intervention, related_name='+', null=True, blank=True, on_delete=models.PROTECT)
    interv_6 = models.ForeignKey(Intervention, related_name='+', null=True, blank=True, on_delete=models.PROTECT)
    interv_7 = models.ForeignKey(Intervention, related_name='+', null=True, blank=True, on_delete=models.PROTECT)
    interv_8 = models.ForeignKey(Intervention, related_name='+', null=True, blank=True, on_delete=models.PROTECT)
    interv_9 = models.ForeignKey(Intervention, related_name='+', null=True, blank=True, on_delete=models.PROTECT)
    spec_pos1 = models.ForeignKey('TreeSpecies', verbose_name="Essence en position 1",
        null=True, blank=True, related_name='+', on_delete=models.PROTECT)
    spec_pos2 = models.ForeignKey('TreeSpecies', verbose_name="Essence en position 2",
        null=True, blank=True, related_name='+', on_delete=models.PROTECT)
    spec_pos3 = models.ForeignKey('TreeSpecies', verbose_name="Essence en position 3",
        null=True, blank=True, related_name='+', on_delete=models.PROTECT)

imports/templates/imports/checkfbase.html
{% extends "base.html" %}

{% block extra_head %}
<style>
    div.fbase-diff { font-family: monospace; margin-bottom: 1em; }
    span.diff { color: red; }
</style>
{% endblock %}

{% block content %}

<h2>Contrôle des chaînes FBase</h2>

<p>Fichier COR: <a href="{{ imp.ifile.url }}">{{ imp.ifile }}</a></p>
<p>Points importés: {{ imp.plotobs_set.count }}</p>
<p>Points avec erreurs non importés: {{ imp.errors.count }}</p>

<h3>Comparaisons FBase:</h3>
{{ imp.fbase_check.identical }} chaînes identiques{% if not imp.fbase_check.different and not imp.fbase_check.errors %}, parfait !{% endif %}
{% if imp.fbase_check.errors %}
    <p>{{ imp.fbase_check.errors }} erreur(s), (impossibilité de comparaison avec base AME)</p>
{% endif %}
{% if imp.fbase_check.different %}
    <br>{{ imp.fbase_check.different|length }} chaîne(s) différente(s):
    {% for diff in imp.fbase_check.different %}
    <div class="fbase-diff">
        <div>AME: {{ diff.0|safe }}</div>
        <div>Our: {{ diff.1|safe }}</div>
    </div>
    {% endfor %}
{% endif %}

{% endblock %}

imports/templates/imports/import.html
{% extends "base.html" %}
{% load static display %}

{% block extra_head %}
<style type="text/css">
table#frm th { width: 25%; text-align: right; vertical-align: top; }
table#interv input { width: 300px; }
legend { font-weight: bold; }
div.vocabulary { font-size: x-small; color: #666; }
div.vocabulary p { margin: 0; }
ul.errors { list-style-type: none; }
ul.errors li { margin-bottom: 1em; border: 1px solid #ccc; }
div.context_line { font-family: monospace; color: #777; font-style: italic; }
span.error { color: red; }
div.error_location { background-color: #eee; padding: 5px; }
div.error_details { padding: 5px; }
span.raw_line { font-family: monospace; }
span.help_text { color: #aaa; font-style: italic; font-size: small; }
</style>
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
<script>
$(document).ready(function() {
    $("select#id_vocab_pos16, select#id_vocab_pos17, select#id_vocab_posd6, select#id_vocab_posd7").on('change', function() {
        // When a vocabulary is selected, display its values in a div
        var field_name = this.id.slice(3);
        if (this.value == "")
            $("div#" + field_name + "_details").html("");
        else
            $("div#" + field_name + "_details").load("/vocabulary/" + this.value + "/");
    });
});
</script>
{% endblock %}

{% block content %}
<h2>Formulaire d'importation de données</h2>

{% if form.instance.pk and not form.instance.imported %}
<p style="color: red">Ce fichier n'a pas été importé car il contient <a href="#errors">des erreurs</a>.</p>
{% endif %}

<form method="POST" enctype="multipart/form-data" action=".">{% csrf_token %}
  <table id="frm">
  <tr><th>Fichier à importer :</th><td>{{ form.ifile.errors }}{{ form.ifile }}</td></tr>
  <tr><th>{{ form.year.label_tag }}</th><td>{{ form.year.errors }}{{ form.year }}</td></tr>
  <tr><td></td><td>{{ form.cont_on_error }} {{ form.cont_on_error.label }}</td></tr>
  </table>
  <p><input type="submit" value="Importer"></p>

{% if form.error_fset %}
  <h2 style="color: red"><a name="errors">Erreurs</a></h2>
  {{ form.error_fset.management_form }}
  <ul class="errors">
  {% for errform in form.error_fset %}
    <li>
        <div class="error_location">Ligne {{ errform.instance.no_line }}: {{ errform.instance.message }}</div>
        <div class="error_details">
            {% for ctxt in errform.instance.context.before %}
                <div class="context_line">{{ ctxt }}</div>
            {% endfor %}
            <span class="raw_line">{{ errform.instance.get_raw_line|safe }}</span><br>
            {{ errform.fixed.errors }}Correction: {{ errform.fixed }} <span class="help_text">{{ errform.fixed.help_text }}</span>
            {% for ctxt in errform.instance.context.after %}
                <div class="context_line">{{ ctxt }}</div>
            {% endfor %}
            {% with ame_record=errform.instance.ame_record %}
            {% if ame_record %}
            <details>
                <summary>Valeurs AME</summary>
                <div class="amerecord">{{ errform.instance.ame_record|instance_fields }}</div>
            </details>
            {% endif %}
            {% endwith %}
        </div>
        {{ errform.id }}
    </li>
  {% endfor %}
  </ul>
{% endif %}

</form>
{% endblock %}

imports/templates/imports/list.html
{% extends "base.html" %}
{% load display %}

{% block extra_head %}
<style>
  table th { text-align: left; background-color: #ddd; }
  table th, table td { padding: 5px; }
  table tr.imported { background-color: #B8F6B8; }
  table tr.imported_with_errors { background-color: #FFE09A; }
  table tr.not_imported { background-color: #FFABB2; }
  table td.fbase-hasdiff { background-color: #FFE09A; }
</style>
{% endblock %}

{% block content %}
<ul>
  <li><a href="{% url 'import' 0 %}">Importer un nouveau fichier</a></li>
</ul>

<h2>Liste des fichiers importés</h2>
<table width="100%">
  <tr>
      <th>Fichier</th><th>Protocole</th><th>Importé ?</th><th>Succès</th><th>Erreurs</th><th></th><th>Ctrl FBase</th>
  </tr>
{% for item in object_list %}
  <tr class="{{ item.status }}">
      <td><a href="{{ item.ifile.url }}">{{ item.ifile|basename }}</a> ({{ item.year }})</td>
      <td>
          {% for prot_pk in protocols|getitem:item.pk %}
            <a href="{% url 'protocole_edit' prot_pk %}">{{ prot_pk }}</a> {% empty %}-
          {% endfor %}
      </td>
      <td>{{ item.imported|yesno:"Oui,Non" }}</td>
      <td>{{ item.succ }}</td>
      <td>{{ item.errs }}</td>
      <td><a href="{% url 'import' item.pk %}">Réimporter</a></td>
      <td {% if not item.fbase_ok %}class="fbase-hasdiff"{% endif %}>
          <a href="{% url 'checkfbase' item.pk %}">
          {% if item.fbase_check %}
            OK: {{ item.fbase_check.identical }}
            {% if item.fbase_check.errors %}<br>Errs: {{ item.fbase_check.errors }}{% endif %}
            {% if item.fbase_check.different %}<br>Diff: {{ item.fbase_check.different|length }}{% endif %}
          {% else %}??{% endif %}
          </a>
      </td>
  </tr>
{% endfor %}
</table>
{% endblock %}